### ISSUE TITLE
Breaking changes within patch release - `1.0.1`

### ISSUE THREAD

**Issue by DDtKey** [maciejhirsz/tiny-bip39#52]
Firs of all, thank you for the maintenance! 

Recently released version `1.0.1` included this PR: #48

Which changed public type, this is breaking change and broke some dependent crates (e.g [pattern matching in atuin](https://github.com/atuinsh/atuin/blob/80e950c648453f2b0fb5987ae01e3f24c7c819d9/crates/atuin-client/src/login.rs#L29))

I'd suggest to yank the version and release major patch instead

**Comment by xpe** [comment]
I also found my way here because of the downstream results to [atuin](https://github.com/atuinsh/atuin).

To expand on what @DDtKey wrote, see also:
* [Stack Overflow: What exactly is considered a breaking change to a library crate?](https://stackoverflow.com/questions/41185023/what-exactly-is-considered-a-breaking-change-to-a-library-crate)
* [RFC 1105: API Evolution](https://github.com/rust-lang/rfcs/blob/master/text/1105-api-evolution.md)

For what it is worth, many of the things listed above are not obvious, at least not without quite a bit of forethought. We're all learning.

**Comment by xpe** [comment]
@maciejhirsz Thanks. This is also what sometimes happens you build a library that other people use. 😄

**Comment by ellie** [comment]
Thank you! Appreciate your work here btw ❤️ 

Otherwise, I'm going to take the opportunity to plug @obi1kenobi's https://github.com/obi1kenobi/cargo-semver-checks. He's spent a long time working on this problem and has produced some excellent tooling to try and catch it before it becomes an issue.

**Comment by obi1kenobi** [comment]
Thanks for the kind words, Ellie 😊

`cargo-semver-checks` isn't perfect yet, but it already has 90+ lints flagging various kinds of breakage. In this case, it wouldn't have caught the type change (https://github.com/obi1kenobi/cargo-semver-checks/issues/149), but its `enum_unit_variant_changed_kind` lint would have caught the breaking change [here](https://github.com/maciejhirsz/tiny-bip39/pull/48/files#diff-97e25e2a0e41c578875856e97b659be2719a65227c104b992e3144efa000c35eR8-R9) in the `ErrorKind::InvalidWord` variant.

I'd be happy to answer any questions folks here might have!

**Comment by maciejhirsz** [comment]
Released 2.0.0, 1.0.1 got yanked. Thank you and apologies :pray:.

**Comment by ellie** [comment]
Thanks for the speedy fix!

**Comment by DDtKey** [comment]
Thank you @maciejhirsz! 🙏
